name: Deploy to GitHub Pages

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          echo "node_modules" >> .gitignore
          git checkout --orphan gh-pages
          git --set-upstream-to=origin/main
          git pull --rebase
          rm -rf *
          mv build/* .
          git add -A
          git commit -m "Auto-deploy to GitHub Pages"
          git push -f origin gh-pages

      - name: Cleanup
        run: |
          git checkout main
          git branch -D gh-pages
